apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: 2019-02-14T17:42:14Z
    name: quay-enterprise-registry
    namespace: quay-enterprise
    resourceVersion: "1605161"
    selfLink: /apis/route.openshift.io/v1/namespaces/quay-enterprise/routes/quay-enterprise-registry
    uid: dd26dee8-307f-11e9-9fa1-16756ab2afa0
  spec:
    host: quay-enterprise-registry-quay-enterprise.apps.sonatype2-da83.openshiftworkshop.com
    port:
      targetPort: https
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: quay-enterprise
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2019-02-14T17:42:14Z
        status: "True"
        type: Admitted
      host: quay-enterprise-registry-quay-enterprise.apps.sonatype2-da83.openshiftworkshop.com
      routerName: router
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: 2019-02-14T17:41:42Z
    name: quay-enterprise-web
    namespace: quay-enterprise
    resourceVersion: "1605123"
    selfLink: /apis/route.openshift.io/v1/namespaces/quay-enterprise/routes/quay-enterprise-web
    uid: ca39a30e-307f-11e9-9fa1-16756ab2afa0
  spec:
    host: quay-enterprise-web-quay-enterprise.apps.sonatype2-da83.openshiftworkshop.com
    port:
      targetPort: http
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: quay-enterprise
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2019-02-14T17:41:42Z
        status: "True"
        type: Admitted
      host: quay-enterprise-web-quay-enterprise.apps.sonatype2-da83.openshiftworkshop.com
      routerName: router
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
